ALTER TABLE `Service` ADD COLUMN `color` VARCHAR(20) NULL;
ALTER TABLE `Staff` ADD COLUMN `photoUrl` VARCHAR(500) NULL;
ALTER TABLE `Service` ADD COLUMN `color` VARCHAR(20) NULL;
ALTER TABLE `Staff` ADD COLUMN `photoUrl` VARCHAR(500) NULL;
